# routes/council_routes.py
"""Council reports API — queue a report run, approval inbox, approve/dismiss.

Agent Council Phase 2 (docs/plans/agent-council-projects-tab.md). Reports are
generated by department agents and only ever *generate* — the human approves
or dismisses from the draft queue. Rows are owner-scoped like projects/notes;
report types are an allowlist (they name template files on disk).
"""

import asyncio
import json
import logging
import uuid
from typing import Any, Dict, Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from core.database import Project, Report, SessionLocal
from services.council.runner import run_report
from src.auth_helpers import get_current_user

logger = logging.getLogger(__name__)

# Allowed report types → (department, title prefix). Phase 3 adds the rest of
# the departments; the allowlist is the guard because report_type names a
# template file on disk.
REPORT_TYPES = {
    "developer_review": ("developer", "Developer Review"),
}

VALID_TRANSITIONS = {"approve": "approved", "dismiss": "dismissed"}

_report_tasks: set = set()


class CreateReportRequest(BaseModel):
    project_id: str
    report_type: str = "developer_review"


def _report_to_dict(r: Report, include_body: bool = False) -> Dict[str, Any]:
    try:
        scores = json.loads(r.scores) if r.scores else {}
    except (json.JSONDecodeError, TypeError):
        scores = {}
    out = {
        "id": r.id,
        "project_id": r.project_id,
        "department": r.department,
        "report_type": r.report_type,
        "title": r.title,
        "status": r.status,
        "error": r.error,
        "model": r.model,
        "scores": scores,
        "created_at": r.created_at.isoformat() if r.created_at else None,
        "finished_at": r.finished_at.isoformat() if r.finished_at else None,
    }
    if include_body:
        out["body"] = r.body
    return out


def setup_council_routes():
    router = APIRouter(prefix="/api/council", tags=["council"])

    def _owner(request: Request) -> Optional[str]:
        return get_current_user(request)

    def _get_owned_report(db, rid: str, user: Optional[str]) -> Report:
        q = db.query(Report).filter(Report.id == rid)
        if user is not None:
            q = q.filter(Report.owner == user)
        report = q.first()
        if not report:
            raise HTTPException(status_code=404, detail="Report not found")
        return report

    @router.post("/reports")
    async def create_report(body: CreateReportRequest, request: Request):
        user = _owner(request)
        if body.report_type not in REPORT_TYPES:
            raise HTTPException(status_code=400, detail="Unknown report type")
        department, title_prefix = REPORT_TYPES[body.report_type]

        db = SessionLocal()
        try:
            q = db.query(Project).filter(Project.id == body.project_id)
            if user is not None:
                q = q.filter(Project.owner == user)
            project = q.first()
            if not project:
                raise HTTPException(status_code=404, detail="Project not found")

            rid = uuid.uuid4().hex[:12]
            db.add(Report(
                id=rid,
                owner=user,
                project_id=project.id,
                department=department,
                report_type=body.report_type,
                title=f"{title_prefix}: {project.name}",
                status="running",
            ))
            db.commit()
        finally:
            db.close()

        task = asyncio.create_task(run_report(rid))
        _report_tasks.add(task)
        task.add_done_callback(_report_tasks.discard)
        return {"report_id": rid, "status": "running"}

    @router.get("/reports")
    def list_reports(request: Request, status: Optional[str] = None,
                     project_id: Optional[str] = None):
        user = _owner(request)
        db = SessionLocal()
        try:
            q = db.query(Report)
            if user is not None:
                q = q.filter(Report.owner == user)
            if status:
                q = q.filter(Report.status == status)
            if project_id:
                q = q.filter(Report.project_id == project_id)
            reports = q.order_by(Report.created_at.desc()).all()
            return {"reports": [_report_to_dict(r) for r in reports]}
        finally:
            db.close()

    @router.get("/reports/{rid}")
    def report_detail(rid: str, request: Request):
        user = _owner(request)
        db = SessionLocal()
        try:
            return _report_to_dict(_get_owned_report(db, rid, user), include_body=True)
        finally:
            db.close()

    def _transition(rid: str, request: Request, action: str):
        user = _owner(request)
        db = SessionLocal()
        try:
            report = _get_owned_report(db, rid, user)
            if report.status != "draft":
                raise HTTPException(
                    status_code=409,
                    detail=f"Only draft reports can be {VALID_TRANSITIONS[action]} "
                           f"(current status: {report.status})",
                )
            report.status = VALID_TRANSITIONS[action]
            db.commit()
            return {"id": rid, "status": report.status}
        finally:
            db.close()

    @router.post("/reports/{rid}/approve")
    def approve_report(rid: str, request: Request):
        return _transition(rid, request, "approve")

    @router.post("/reports/{rid}/dismiss")
    def dismiss_report(rid: str, request: Request):
        return _transition(rid, request, "dismiss")

    return router
