# routes/council_routes.py
"""Council reports API — queue a report run, approval inbox, approve/dismiss.

Agent Council Phase 2 (docs/plans/agent-council-projects-tab.md). Reports are
generated by department agents and only ever *generate* — the human approves
or dismisses from the draft queue. Rows are owner-scoped like projects/notes;
report types are an allowlist (they name template files on disk).
"""

import asyncio
import json
import logging
import uuid
from typing import Any, Dict, Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from core.database import CrewMember, Project, Report, SessionLocal
from services.council.personas import seed_council_members
from services.council.runner import (
    COMPONENT_TYPES as REPORT_TYPES,
    queue_state,
    run_full_council,
    run_report,
)
from src.auth_helpers import get_current_user

logger = logging.getLogger(__name__)

# Single-report allowlist → (department, title prefix). Sourced from the runner
# so the route and the full-council orchestrator never drift; the meta
# ``council_review`` type is deliberately excluded (only the orchestrator makes
# one). The allowlist is the guard because report_type names a template on disk.

VALID_TRANSITIONS = {"approve": "approved", "dismiss": "dismissed"}

_report_tasks: set = set()


class CreateReportRequest(BaseModel):
    project_id: str
    report_type: str = "developer_review"


class RunFullRequest(BaseModel):
    project_id: str


class UpdateMemberRequest(BaseModel):
    name: Optional[str] = None
    avatar: Optional[str] = None
    personality: Optional[str] = None
    model: Optional[str] = None
    endpoint_url: Optional[str] = None


def _member_to_dict(m: CrewMember) -> Dict[str, Any]:
    return {
        "id": m.id,
        "department": m.department,
        "name": m.name,
        "avatar": m.avatar,
        "personality": m.personality,
        "model": m.model,
        "endpoint_url": m.endpoint_url,
    }


def _report_to_dict(r: Report, include_body: bool = False) -> Dict[str, Any]:
    try:
        scores = json.loads(r.scores) if r.scores else {}
    except (json.JSONDecodeError, TypeError):
        scores = {}
    out = {
        "id": r.id,
        "project_id": r.project_id,
        "department": r.department,
        "report_type": r.report_type,
        "title": r.title,
        "status": r.status,
        "error": r.error,
        "model": r.model,
        "scores": scores,
        "created_at": r.created_at.isoformat() if r.created_at else None,
        "finished_at": r.finished_at.isoformat() if r.finished_at else None,
    }
    if include_body:
        out["body"] = r.body
    return out


def setup_council_routes():
    router = APIRouter(prefix="/api/council", tags=["council"])

    def _owner(request: Request) -> Optional[str]:
        return get_current_user(request)

    def _get_owned_report(db, rid: str, user: Optional[str]) -> Report:
        q = db.query(Report).filter(Report.id == rid)
        if user is not None:
            q = q.filter(Report.owner == user)
        report = q.first()
        if not report:
            raise HTTPException(status_code=404, detail="Report not found")
        return report

    @router.post("/reports")
    async def create_report(body: CreateReportRequest, request: Request):
        user = _owner(request)
        if body.report_type not in REPORT_TYPES:
            raise HTTPException(status_code=400, detail="Unknown report type")
        department, title_prefix = REPORT_TYPES[body.report_type]

        db = SessionLocal()
        try:
            q = db.query(Project).filter(Project.id == body.project_id)
            if user is not None:
                q = q.filter(Project.owner == user)
            project = q.first()
            if not project:
                raise HTTPException(status_code=404, detail="Project not found")

            rid = uuid.uuid4().hex[:12]
            db.add(Report(
                id=rid,
                owner=user,
                project_id=project.id,
                department=department,
                report_type=body.report_type,
                title=f"{title_prefix}: {project.name}",
                status="running",
            ))
            db.commit()
        finally:
            db.close()

        task = asyncio.create_task(run_report(rid))
        _report_tasks.add(task)
        task.add_done_callback(_report_tasks.discard)
        return {"report_id": rid, "status": "running"}

    @router.post("/run-full")
    async def run_full(body: RunFullRequest, request: Request):
        """Run every department review for a project, then a unified council
        synthesis — one click, drafted for approval."""
        user = _owner(request)
        db = SessionLocal()
        try:
            q = db.query(Project).filter(Project.id == body.project_id)
            if user is not None:
                q = q.filter(Project.owner == user)
            if not q.first():
                raise HTTPException(status_code=404, detail="Project not found")
        finally:
            db.close()

        task = asyncio.create_task(run_full_council(body.project_id, user))
        _report_tasks.add(task)
        task.add_done_callback(_report_tasks.discard)
        return {"status": "running"}

    @router.get("/reports")
    def list_reports(request: Request, status: Optional[str] = None,
                     project_id: Optional[str] = None):
        user = _owner(request)
        db = SessionLocal()
        try:
            q = db.query(Report)
            if user is not None:
                q = q.filter(Report.owner == user)
            if status:
                q = q.filter(Report.status == status)
            if project_id:
                q = q.filter(Report.project_id == project_id)
            reports = q.order_by(Report.created_at.desc()).all()
            return {"reports": [_report_to_dict(r) for r in reports]}
        finally:
            db.close()

    @router.get("/reports/{rid}")
    def report_detail(rid: str, request: Request):
        user = _owner(request)
        db = SessionLocal()
        try:
            return _report_to_dict(_get_owned_report(db, rid, user), include_body=True)
        finally:
            db.close()

    def _transition(rid: str, request: Request, action: str):
        user = _owner(request)
        db = SessionLocal()
        try:
            report = _get_owned_report(db, rid, user)
            if report.status != "draft":
                raise HTTPException(
                    status_code=409,
                    detail=f"Only draft reports can be {VALID_TRANSITIONS[action]} "
                           f"(current status: {report.status})",
                )
            report.status = VALID_TRANSITIONS[action]
            db.commit()
            return {"id": rid, "status": report.status}
        finally:
            db.close()

    @router.get("/status")
    def council_status(request: Request):
        user = _owner(request)
        # First council use seeds the five default members (idempotent).
        seed_council_members(user, session_factory=SessionLocal)

        state = queue_state()
        db = SessionLocal()
        try:
            # Departments of the running/queued reports, owner-scoped so one
            # user's queue never leaks into another's dashboard.
            ids = [i for i in [state["running"], *state["queued"]] if i]
            q = db.query(Report).filter(Report.id.in_(ids)) if ids else []
            if ids and user is not None:
                q = q.filter(Report.owner == user)
            dept_of = {r.id: r.department for r in q}

            queue_position = {}
            for pos, rid in enumerate(state["queued"], start=1):
                if rid in dept_of:
                    queue_position.setdefault(dept_of[rid], pos)

            mq = db.query(CrewMember).filter(CrewMember.department.isnot(None))
            if user is not None:
                mq = mq.filter(CrewMember.owner == user)
            members = []
            running_dept = dept_of.get(state["running"])
            for m in mq.order_by(CrewMember.name).all():
                if m.department == running_dept:
                    status, current = "Busy", state["running"]
                else:
                    status, current = "Ready", None
                pos = queue_position.get(m.department)
                if status == "Ready" and pos:
                    status = "Waiting"
                members.append({
                    "department": m.department,
                    "name": m.name,
                    "avatar": m.avatar,
                    "status": status,
                    "current_report_id": current,
                    "queue_position": pos,
                })
            return {"members": members}
        finally:
            db.close()

    @router.get("/members")
    def list_members(request: Request):
        user = _owner(request)
        seed_council_members(user, session_factory=SessionLocal)  # idempotent
        db = SessionLocal()
        try:
            q = db.query(CrewMember).filter(CrewMember.department.isnot(None))
            if user is not None:
                q = q.filter(CrewMember.owner == user)
            members = q.order_by(CrewMember.name).all()
            return {"members": [_member_to_dict(m) for m in members]}
        finally:
            db.close()

    @router.put("/members/{mid}")
    def update_member(mid: str, body: UpdateMemberRequest, request: Request):
        user = _owner(request)
        db = SessionLocal()
        try:
            q = db.query(CrewMember).filter(CrewMember.id == mid)
            if user is not None:
                q = q.filter(CrewMember.owner == user)
            member = q.first()
            if not member:
                raise HTTPException(status_code=404, detail="Member not found")
            # Only the editable fields — department is never reset by an edit.
            for field in ("name", "avatar", "personality", "model", "endpoint_url"):
                val = getattr(body, field)
                if val is not None:
                    setattr(member, field, val)
            db.commit()
            return _member_to_dict(member)
        finally:
            db.close()

    @router.post("/reports/{rid}/approve")
    def approve_report(rid: str, request: Request):
        return _transition(rid, request, "approve")

    @router.post("/reports/{rid}/dismiss")
    def dismiss_report(rid: str, request: Request):
        return _transition(rid, request, "dismiss")

    return router
